apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: gen-ai-pipeline
  
description: Delivery pipeline for Gen AI application
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
    - targetId: prod
      profiles: []