apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels:
        app: gemini-app
    spec:
      containers:
      - name: gemini-app
        image: gcr.io/regal-scholar-423322-h0/gemini-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "mykey.json"
      #   volumeMounts:
      #   - name: credentials
      #     mountPath: /path/to/your
      # volumes:
      # - name: credentials
      #   secret:
      #     secretName: gcp-key-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-app-service
spec:
  type: LoadBalancer
  selector:
    app: gemini-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
