# Deployment for Development Namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app
  namespace: dev-target
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels:
        app: gemini-app
    spec:
      containers:
        - name: gemini-app
          image: gemini-app:latest
          ports:
            - containerPort: 80
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "my_key.json"
            - name: PORT
              value: "80"
            - name: API_KEY
              value: "AIzaSyAM2gXjIhpYNGu3WNQsXKEy36DFecJIRVw"
---
# Service for Development Namespace
apiVersion: v1
kind: Service
metadata:
  name: gemini-app
  namespace: dev-target
spec:
  selector:
    app: gemini-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
# Deployment for Production Namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-app
  namespace: prod-target
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels:
        app: gemini-app
    spec:
      containers:
        - name: gemini-app
          image: gemini-app:latest
          ports:
            - containerPort: 80
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "my_key.json"
            - name: PORT
              value: "80"
            - name: API_KEY
              value: "AIzaSyAM2gXjIhpYNGu3WNQsXKEy36DFecJIRVw"
---
# Service for Production Namespace
apiVersion: v1
kind: Service
metadata:
  name: gemini-app
  namespace: prod-target
spec:
  selector:
    app: gemini-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
