apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: gemini-app
build:
  artifacts:
    - image: gemini-app
deploy:
  kubectl:
    manifests:
      - kubernetes.yaml
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - dev-target.yaml
  - name: prod
    deploy:
      kubectl:
        manifests:
          - prod-target.yaml